
module.exports = {


  "chargeInfoWorkflow":[{
                          ID: "0",
                          changeType: "transfer",
                          region: "anglian",
                          type: ["charge information"],
                          licence: "00/22/001/02",
                          licenceStartDate: "20200131",
                          licenceHolder: "Irene Briton",
                          status: "to set up",
                          billedUpto: "20210331",
                          setUpBy: "",
                          chargeInfoStartDate: "20200131",
                          changeRequest: "",
                        },
                        {
                          ID: "0",
                          changeType: "transfer",
                          region: "anglian",
                          type: ["charge information"],
                          licence: "test2",
                          licenceStartDate: "20200131",
                          licenceHolder: "Irene Briton",
                          status: "to set up",
                          billedUpto: "20210331",
                          setUpBy: "",
                          chargeInfoStartDate: "20200131",
                          changeRequest: "",
                        },
                        {
                          ID: "0",
                          changeType: "transfer",
                          region: "anglian",
                          type: ["returns requirements"],
                          licence: "test3",
                          licenceStartDate: "20200131",
                          licenceHolder: "Irene Briton",
                          status: "to set up",
                          billedUpto: "20210331",
                          setUpBy: "",
                          chargeInfoStartDate: "20200131",
                          changeRequest: "",
                        },
                        {
                          ID: "0",
                          changeType: "transfer",
                          region: "anglian",
                          type: ["charge information","returns requirements"],
                          licence: "test4",
                          licenceStartDate: "20200131",
                          licenceHolder: "Irene Briton",
                          status: "to set up",
                          billedUpto: "20210331",
                          setUpBy: "",
                          chargeInfoStartDate: "20200131",
                          changeRequest: "",
                        },
                        { 
                          ID: "2",
                          changeType: "transfer",
                          region: "anglian",
                          type: ["returns requirements"],
                          licence: "03/28/61/0290",
                          licenceStartDate: "20220401",
                          licenceHolder: "Big Smith Farms Ltd",
                          status: "review",
                          billedUpto: "",
                          setUpBy: "michael.babb@madeup.com", 
                          chargeInfoStartDate: "20220401",
                          changeRequest: "",
                        },
                        { 
                          ID: "5",
                          changeType: "variation",
                          region: "south west",
                          type: ["charge information"],
                          licence: "03/28/60/0726",
                          licenceStartDate: "20200131",
                          licenceHolder: "Robin Vithlhem-Smith",
                          status: "review",
                          billedUpto: "",
                          setUpBy: "michael.babb@madeup.com",
                          chargeInfoStartDate: "20200131",
                          changeRequest: "",
                        },
                        { 
                          ID: "6",
                          changeType: "new licence",
                          region: "midlands",
                          type: ["charge information"],
                          licence: "11/22/32/02",
                          licenceStartDate: "20200131",
                          licenceHolder: "D.B. Beecham-Smith",
                          status: "change request",
                          billedUpto: "20210331",
                          setUpBy: "	emma.nevin@madeup.com",
                          chargeInfoStartDate: "20200131",
                          changeRequest: "Please change the abstraction start month to April",
                         },
                     ]


}
